//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TableProto.proto
namespace TableProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActionAudioInfo")]
  public partial class ActionAudioInfo : global::ProtoBuf.IExtensible
  {
    public ActionAudioInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _audio_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"audio_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string audio_name
    {
      get { return _audio_name; }
      set { _audio_name = value; }
    }

    private int _play_state = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"play_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int play_state
    {
      get { return _play_state; }
      set { _play_state = value; }
    }

    private int _play_path = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"play_path", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int play_path
    {
      get { return _play_path; }
      set { _play_path = value; }
    }

    private int _play_mode = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"play_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int play_mode
    {
      get { return _play_mode; }
      set { _play_mode = value; }
    }

    private string _action_param_array = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"action_param_array", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string action_param_array
    {
      get { return _action_param_array; }
      set { _action_param_array = value; }
    }

    private uint _audio_delay_time = (uint)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"audio_delay_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint audio_delay_time
    {
      get { return _audio_delay_time; }
      set { _audio_delay_time = value; }
    }

    private string _action_end_name = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"action_end_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string action_end_name
    {
      get { return _action_end_name; }
      set { _action_end_name = value; }
    }

    private uint _action_end_time = (uint)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"action_end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint action_end_time
    {
      get { return _action_end_time; }
      set { _action_end_time = value; }
    }

    private uint _next_action_id = (uint)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"next_action_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint next_action_id
    {
      get { return _next_action_id; }
      set { _next_action_id = value; }
    }

    private string _audio_describe = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"audio_describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string audio_describe
    {
      get { return _audio_describe; }
      set { _audio_describe = value; }
    }

    private string _describe = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string describe
    {
      get { return _describe; }
      set { _describe = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActionAudioInfo_ARRAY")]
  public partial class ActionAudioInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public ActionAudioInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<ActionAudioInfo> _items = new global::System.Collections.Generic.List<ActionAudioInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionAudioInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorInfo")]
  public partial class ActorInfo : global::ProtoBuf.IExtensible
  {
    public ActorInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _res_path;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"res_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string res_path
    {
      get { return _res_path; }
      set { _res_path = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorInfo_ARRAY")]
  public partial class ActorInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public ActorInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<ActorInfo> _items = new global::System.Collections.Generic.List<ActorInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActorInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AudioEnglishInfo")]
  public partial class AudioEnglishInfo : global::ProtoBuf.IExtensible
  {
    public AudioEnglishInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _play_state = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"play_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int play_state
    {
      get { return _play_state; }
      set { _play_state = value; }
    }

    private int _play_mode = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"play_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int play_mode
    {
      get { return _play_mode; }
      set { _play_mode = value; }
    }

    private int _play_path = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"play_path", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int play_path
    {
      get { return _play_path; }
      set { _play_path = value; }
    }

    private string _action_describe = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"action_describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string action_describe
    {
      get { return _action_describe; }
      set { _action_describe = value; }
    }

    private string _audio_describe = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"audio_describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string audio_describe
    {
      get { return _audio_describe; }
      set { _audio_describe = value; }
    }

    private string _describe = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string describe
    {
      get { return _describe; }
      set { _describe = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AudioEnglishInfo_ARRAY")]
  public partial class AudioEnglishInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public AudioEnglishInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<AudioEnglishInfo> _items = new global::System.Collections.Generic.List<AudioEnglishInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AudioEnglishInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AudioInfo")]
  public partial class AudioInfo : global::ProtoBuf.IExtensible
  {
    public AudioInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _play_state = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"play_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int play_state
    {
      get { return _play_state; }
      set { _play_state = value; }
    }

    private int _play_mode = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"play_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int play_mode
    {
      get { return _play_mode; }
      set { _play_mode = value; }
    }

    private int _play_path = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"play_path", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int play_path
    {
      get { return _play_path; }
      set { _play_path = value; }
    }

    private string _action_describe = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"action_describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string action_describe
    {
      get { return _action_describe; }
      set { _action_describe = value; }
    }

    private string _audio_describe = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"audio_describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string audio_describe
    {
      get { return _audio_describe; }
      set { _audio_describe = value; }
    }

    private string _describe = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string describe
    {
      get { return _describe; }
      set { _describe = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AudioInfo_ARRAY")]
  public partial class AudioInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public AudioInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<AudioInfo> _items = new global::System.Collections.Generic.List<AudioInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AudioInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnglishColoursInfo")]
  public partial class EnglishColoursInfo : global::ProtoBuf.IExtensible
  {
    public EnglishColoursInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _word = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"word", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string word
    {
      get { return _word; }
      set { _word = value; }
    }

    private string _wordAudio = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"wordAudio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wordAudio
    {
      get { return _wordAudio; }
      set { _wordAudio = value; }
    }

    private string _wordAudioArray = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"wordAudioArray", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string wordAudioArray
    {
      get { return _wordAudioArray; }
      set { _wordAudioArray = value; }
    }

    private string _fillColor = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fillColor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fillColor
    {
      get { return _fillColor; }
      set { _fillColor = value; }
    }

    private string _secondWordAudio = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"secondWordAudio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string secondWordAudio
    {
      get { return _secondWordAudio; }
      set { _secondWordAudio = value; }
    }

    private string _ColorTexName = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ColorTexName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ColorTexName
    {
      get { return _ColorTexName; }
      set { _ColorTexName = value; }
    }

    private string _SpecialColor = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"SpecialColor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SpecialColor
    {
      get { return _SpecialColor; }
      set { _SpecialColor = value; }
    }

    private string _mainTex = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"mainTex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mainTex
    {
      get { return _mainTex; }
      set { _mainTex = value; }
    }

    private string _mainTexAudio = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"mainTexAudio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mainTexAudio
    {
      get { return _mainTexAudio; }
      set { _mainTexAudio = value; }
    }

    private string _mainTexAudioWord = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"mainTexAudioWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mainTexAudioWord
    {
      get { return _mainTexAudioWord; }
      set { _mainTexAudioWord = value; }
    }

    private string _mainTexWordAudio = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"mainTexWordAudio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mainTexWordAudio
    {
      get { return _mainTexWordAudio; }
      set { _mainTexWordAudio = value; }
    }

    private string _texFillCompleteThrehold = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"texFillCompleteThrehold", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string texFillCompleteThrehold
    {
      get { return _texFillCompleteThrehold; }
      set { _texFillCompleteThrehold = value; }
    }

    private string _randomTex = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"randomTex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string randomTex
    {
      get { return _randomTex; }
      set { _randomTex = value; }
    }

    private string _randomTexAudio = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"randomTexAudio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string randomTexAudio
    {
      get { return _randomTexAudio; }
      set { _randomTexAudio = value; }
    }

    private string _randomTexAudioWord = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"randomTexAudioWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string randomTexAudioWord
    {
      get { return _randomTexAudioWord; }
      set { _randomTexAudioWord = value; }
    }

    private string _randomTexWordAudio = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"randomTexWordAudio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string randomTexWordAudio
    {
      get { return _randomTexWordAudio; }
      set { _randomTexWordAudio = value; }
    }

    private string _des = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"des", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string des
    {
      get { return _des; }
      set { _des = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnglishColoursInfo_ARRAY")]
  public partial class EnglishColoursInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public EnglishColoursInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<EnglishColoursInfo> _items = new global::System.Collections.Generic.List<EnglishColoursInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EnglishColoursInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnglishLetterInfo")]
  public partial class EnglishLetterInfo : global::ProtoBuf.IExtensible
  {
    public EnglishLetterInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _description = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }

    private string _param_1 = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"param_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param_1
    {
      get { return _param_1; }
      set { _param_1 = value; }
    }

    private string _param_2 = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"param_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param_2
    {
      get { return _param_2; }
      set { _param_2 = value; }
    }

    private string _param_3 = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"param_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param_3
    {
      get { return _param_3; }
      set { _param_3 = value; }
    }

    private string _audio_param_1 = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"audio_param_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string audio_param_1
    {
      get { return _audio_param_1; }
      set { _audio_param_1 = value; }
    }

    private string _audio_param_2 = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"audio_param_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string audio_param_2
    {
      get { return _audio_param_2; }
      set { _audio_param_2 = value; }
    }

    private string _audio_param_3 = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"audio_param_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string audio_param_3
    {
      get { return _audio_param_3; }
      set { _audio_param_3 = value; }
    }

    private int _param_1_atlas = (int)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"param_1_atlas", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int param_1_atlas
    {
      get { return _param_1_atlas; }
      set { _param_1_atlas = value; }
    }

    private string _param_1_texture = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"param_1_texture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param_1_texture
    {
      get { return _param_1_texture; }
      set { _param_1_texture = value; }
    }

    private int _param_2_atlas = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"param_2_atlas", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int param_2_atlas
    {
      get { return _param_2_atlas; }
      set { _param_2_atlas = value; }
    }

    private string _param_2_texture = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"param_2_texture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param_2_texture
    {
      get { return _param_2_texture; }
      set { _param_2_texture = value; }
    }

    private int _param_3_atlas = (int)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"param_3_atlas", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int param_3_atlas
    {
      get { return _param_3_atlas; }
      set { _param_3_atlas = value; }
    }

    private string _param_3_texture = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"param_3_texture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param_3_texture
    {
      get { return _param_3_texture; }
      set { _param_3_texture = value; }
    }

    private string _param_1_offset = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"param_1_offset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param_1_offset
    {
      get { return _param_1_offset; }
      set { _param_1_offset = value; }
    }

    private string _param_2_offset = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"param_2_offset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param_2_offset
    {
      get { return _param_2_offset; }
      set { _param_2_offset = value; }
    }

    private string _param_3_offset = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"param_3_offset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param_3_offset
    {
      get { return _param_3_offset; }
      set { _param_3_offset = value; }
    }

    private string _ledi_hint_audio = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"ledi_hint_audio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ledi_hint_audio
    {
      get { return _ledi_hint_audio; }
      set { _ledi_hint_audio = value; }
    }

    private string _letter_draw_audio = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"letter_draw_audio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string letter_draw_audio
    {
      get { return _letter_draw_audio; }
      set { _letter_draw_audio = value; }
    }

    private string _ledi_letter_audio = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"ledi_letter_audio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ledi_letter_audio
    {
      get { return _ledi_letter_audio; }
      set { _ledi_letter_audio = value; }
    }

    private int _bigorsmall = (int)0;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"bigorsmall", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int bigorsmall
    {
      get { return _bigorsmall; }
      set { _bigorsmall = value; }
    }

    private string _game1_statement1 = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"game1_statement1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string game1_statement1
    {
      get { return _game1_statement1; }
      set { _game1_statement1 = value; }
    }

    private string _game1_statement2 = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"game1_statement2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string game1_statement2
    {
      get { return _game1_statement2; }
      set { _game1_statement2 = value; }
    }

    private string _game1_statement3 = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"game1_statement3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string game1_statement3
    {
      get { return _game1_statement3; }
      set { _game1_statement3 = value; }
    }

    private string _game1_statement4 = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"game1_statement4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string game1_statement4
    {
      get { return _game1_statement4; }
      set { _game1_statement4 = value; }
    }

    private string _game1_audio1 = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"game1_audio1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string game1_audio1
    {
      get { return _game1_audio1; }
      set { _game1_audio1 = value; }
    }

    private string _game1_audio2 = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"game1_audio2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string game1_audio2
    {
      get { return _game1_audio2; }
      set { _game1_audio2 = value; }
    }

    private string _game1_audio3 = "";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"game1_audio3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string game1_audio3
    {
      get { return _game1_audio3; }
      set { _game1_audio3 = value; }
    }

    private string _game1_audio4 = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"game1_audio4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string game1_audio4
    {
      get { return _game1_audio4; }
      set { _game1_audio4 = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _game1_bg_list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(31, Name=@"game1_bg_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> game1_bg_list
    {
      get { return _game1_bg_list; }
    }
  

    private string _game1_texture1 = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"game1_texture1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string game1_texture1
    {
      get { return _game1_texture1; }
      set { _game1_texture1 = value; }
    }

    private string _game1_texture2 = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"game1_texture2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string game1_texture2
    {
      get { return _game1_texture2; }
      set { _game1_texture2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnglishLetterInfo_ARRAY")]
  public partial class EnglishLetterInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public EnglishLetterInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<EnglishLetterInfo> _items = new global::System.Collections.Generic.List<EnglishLetterInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EnglishLetterInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnglishLevelInfo")]
  public partial class EnglishLevelInfo : global::ProtoBuf.IExtensible
  {
    public EnglishLevelInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _play_mode = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"play_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int play_mode
    {
      get { return _play_mode; }
      set { _play_mode = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _game_flow_1 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"game_flow_1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> game_flow_1
    {
      get { return _game_flow_1; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _game_flow_2 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"game_flow_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> game_flow_2
    {
      get { return _game_flow_2; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _game_flow_3 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"game_flow_3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> game_flow_3
    {
      get { return _game_flow_3; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _game_flow_4 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"game_flow_4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> game_flow_4
    {
      get { return _game_flow_4; }
    }
  

    private string _word = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"word", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string word
    {
      get { return _word; }
      set { _word = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnglishLevelInfo_ARRAY")]
  public partial class EnglishLevelInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public EnglishLevelInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<EnglishLevelInfo> _items = new global::System.Collections.Generic.List<EnglishLevelInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EnglishLevelInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnglishMainItemInfo")]
  public partial class EnglishMainItemInfo : global::ProtoBuf.IExtensible
  {
    public EnglishMainItemInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private int _shop_info = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"shop_info", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int shop_info
    {
      get { return _shop_info; }
      set { _shop_info = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _show;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"show", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint show
    {
      get { return _show; }
      set { _show = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _index;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }

    private string _scene = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"scene", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string scene
    {
      get { return _scene; }
      set { _scene = value; }
    }

    private int _scene_int = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"scene_int", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int scene_int
    {
      get { return _scene_int; }
      set { _scene_int = value; }
    }

    private string _image = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string image
    {
      get { return _image; }
      set { _image = value; }
    }

    private string _action_asset = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"action_asset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string action_asset
    {
      get { return _action_asset; }
      set { _action_asset = value; }
    }
    private int _download;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"download", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int download
    {
      get { return _download; }
      set { _download = value; }
    }

    private string _path = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }

    private int _main_buy = (int)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"main_buy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int main_buy
    {
      get { return _main_buy; }
      set { _main_buy = value; }
    }

    private string _umeng_event = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"umeng_event", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string umeng_event
    {
      get { return _umeng_event; }
      set { _umeng_event = value; }
    }

    private string _umeng_level = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"umeng_level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string umeng_level
    {
      get { return _umeng_level; }
      set { _umeng_level = value; }
    }

    private string _desc = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnglishMainItemInfo_ARRAY")]
  public partial class EnglishMainItemInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public EnglishMainItemInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<EnglishMainItemInfo> _items = new global::System.Collections.Generic.List<EnglishMainItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EnglishMainItemInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExpressPhotosInfo")]
  public partial class ExpressPhotosInfo : global::ProtoBuf.IExtensible
  {
    public ExpressPhotosInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _title;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _photo_url;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"photo_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string photo_url
    {
      get { return _photo_url; }
      set { _photo_url = value; }
    }
    private uint _area_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"area_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint area_type
    {
      get { return _area_type; }
      set { _area_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExpressPhotosInfo_ARRAY")]
  public partial class ExpressPhotosInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public ExpressPhotosInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<ExpressPhotosInfo> _items = new global::System.Collections.Generic.List<ExpressPhotosInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ExpressPhotosInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MainAnimation")]
  public partial class MainAnimation : global::ProtoBuf.IExtensible
  {
    public MainAnimation() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _special_act;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"special_act", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint special_act
    {
      get { return _special_act; }
      set { _special_act = value; }
    }
    private int _enable;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"enable", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int enable
    {
      get { return _enable; }
      set { _enable = value; }
    }
    private readonly global::System.Collections.Generic.List<MainAnimation.act_attr> _act_table = new global::System.Collections.Generic.List<MainAnimation.act_attr>();
    [global::ProtoBuf.ProtoMember(4, Name=@"act_table", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MainAnimation.act_attr> act_table
    {
      get { return _act_table; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"act_attr")]
  public partial class act_attr : global::ProtoBuf.IExtensible
  {
    public act_attr() {}
    

    private string _act_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"act_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string act_name
    {
      get { return _act_name; }
      set { _act_name = value; }
    }

    private string _act_sound = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"act_sound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string act_sound
    {
      get { return _act_sound; }
      set { _act_sound = value; }
    }

    private uint _time = (uint)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }

    private uint _delay_time = (uint)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"delay_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint delay_time
    {
      get { return _delay_time; }
      set { _delay_time = value; }
    }

    private string _act_des = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"act_des", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string act_des
    {
      get { return _act_des; }
      set { _act_des = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MainAnimation_ARRAY")]
  public partial class MainAnimation_ARRAY : global::ProtoBuf.IExtensible
  {
    public MainAnimation_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<MainAnimation> _items = new global::System.Collections.Generic.List<MainAnimation>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MainAnimation> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MainItemInfo")]
  public partial class MainItemInfo : global::ProtoBuf.IExtensible
  {
    public MainItemInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _show;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"show", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint show
    {
      get { return _show; }
      set { _show = value; }
    }
    private uint _show_ios;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"show_ios", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint show_ios
    {
      get { return _show_ios; }
      set { _show_ios = value; }
    }
    private uint _newtips;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"newtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint newtips
    {
      get { return _newtips; }
      set { _newtips = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _index;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }

    private string _scene = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"scene", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string scene
    {
      get { return _scene; }
      set { _scene = value; }
    }

    private int _scene_int = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"scene_int", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int scene_int
    {
      get { return _scene_int; }
      set { _scene_int = value; }
    }

    private string _image = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string image
    {
      get { return _image; }
      set { _image = value; }
    }

    private string _path = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }

    private int _main_buy = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"main_buy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int main_buy
    {
      get { return _main_buy; }
      set { _main_buy = value; }
    }
    private int _price;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int price
    {
      get { return _price; }
      set { _price = value; }
    }
    private int _price_ios;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"price_ios", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int price_ios
    {
      get { return _price_ios; }
      set { _price_ios = value; }
    }
    private int _download;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"download", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int download
    {
      get { return _download; }
      set { _download = value; }
    }
    private int _download_ios;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"download_ios", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int download_ios
    {
      get { return _download_ios; }
      set { _download_ios = value; }
    }

    private string _shop_bg = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"shop_bg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string shop_bg
    {
      get { return _shop_bg; }
      set { _shop_bg = value; }
    }

    private string _umeng_event = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"umeng_event", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string umeng_event
    {
      get { return _umeng_event; }
      set { _umeng_event = value; }
    }

    private string _umeng_level = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"umeng_level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string umeng_level
    {
      get { return _umeng_level; }
      set { _umeng_level = value; }
    }

    private string _desc = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MainItemInfo_ARRAY")]
  public partial class MainItemInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public MainItemInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<MainItemInfo> _items = new global::System.Collections.Generic.List<MainItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MainItemInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatrixLevel")]
  public partial class MatrixLevel : global::ProtoBuf.IExtensible
  {
    public MatrixLevel() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _rowTitles;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rowTitles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rowTitles
    {
      get { return _rowTitles; }
      set { _rowTitles = value; }
    }
    private string _columnTitles;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"columnTitles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string columnTitles
    {
      get { return _columnTitles; }
      set { _columnTitles = value; }
    }

    private int _rIsRandom = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"rIsRandom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int rIsRandom
    {
      get { return _rIsRandom; }
      set { _rIsRandom = value; }
    }
    private int _cIsRandom;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"cIsRandom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cIsRandom
    {
      get { return _cIsRandom; }
      set { _cIsRandom = value; }
    }

    private string _titleRes = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"titleRes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string titleRes
    {
      get { return _titleRes; }
      set { _titleRes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatrixLevel_ARRAY")]
  public partial class MatrixLevel_ARRAY : global::ProtoBuf.IExtensible
  {
    public MatrixLevel_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<MatrixLevel> _items = new global::System.Collections.Generic.List<MatrixLevel>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MatrixLevel> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatrixLevelInfo")]
  public partial class MatrixLevelInfo : global::ProtoBuf.IExtensible
  {
    public MatrixLevelInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _levelId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"levelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelId
    {
      get { return _levelId; }
      set { _levelId = value; }
    }
    private string _rowTitle;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rowTitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rowTitle
    {
      get { return _rowTitle; }
      set { _rowTitle = value; }
    }
    private string _columnTitle;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"columnTitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string columnTitle
    {
      get { return _columnTitle; }
      set { _columnTitle = value; }
    }
    private string _resultname;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"resultname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string resultname
    {
      get { return _resultname; }
      set { _resultname = value; }
    }

    private int _resRotation = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"resRotation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int resRotation
    {
      get { return _resRotation; }
      set { _resRotation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatrixLevelInfo_ARRAY")]
  public partial class MatrixLevelInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public MatrixLevelInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<MatrixLevelInfo> _items = new global::System.Collections.Generic.List<MatrixLevelInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MatrixLevelInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewBieInfo")]
  public partial class NewBieInfo : global::ProtoBuf.IExtensible
  {
    public NewBieInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _Priority;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Priority
    {
      get { return _Priority; }
      set { _Priority = value; }
    }
    private uint _LevelUpperLimit;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"LevelUpperLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LevelUpperLimit
    {
      get { return _LevelUpperLimit; }
      set { _LevelUpperLimit = value; }
    }
    private uint _LevelLowerLimit;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"LevelLowerLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LevelLowerLimit
    {
      get { return _LevelLowerLimit; }
      set { _LevelLowerLimit = value; }
    }
    private uint _SavePoint;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"SavePoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SavePoint
    {
      get { return _SavePoint; }
      set { _SavePoint = value; }
    }
    private uint _StartTimeType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"StartTimeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StartTimeType
    {
      get { return _StartTimeType; }
      set { _StartTimeType = value; }
    }
    private uint _StartIndex;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"StartIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StartIndex
    {
      get { return _StartIndex; }
      set { _StartIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewBieInfo_ARRAY")]
  public partial class NewBieInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public NewBieInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<NewBieInfo> _items = new global::System.Collections.Generic.List<NewBieInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NewBieInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewBieScript")]
  public partial class NewBieScript : global::ProtoBuf.IExtensible
  {
    public NewBieScript() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _NewbieId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"NewbieId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NewbieId
    {
      get { return _NewbieId; }
      set { _NewbieId = value; }
    }
    private uint _Type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private uint _PauseGame;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"PauseGame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PauseGame
    {
      get { return _PauseGame; }
      set { _PauseGame = value; }
    }
    private string _SoundFileName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"SoundFileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SoundFileName
    {
      get { return _SoundFileName; }
      set { _SoundFileName = value; }
    }
    private uint _ShowTransparency;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ShowTransparency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ShowTransparency
    {
      get { return _ShowTransparency; }
      set { _ShowTransparency = value; }
    }
    private uint _FlipType;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"FlipType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FlipType
    {
      get { return _FlipType; }
      set { _FlipType = value; }
    }
    private uint _NotShowArrow;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"NotShowArrow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NotShowArrow
    {
      get { return _NotShowArrow; }
      set { _NotShowArrow = value; }
    }
    private int _OffsetHighLightX;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"OffsetHighLightX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OffsetHighLightX
    {
      get { return _OffsetHighLightX; }
      set { _OffsetHighLightX = value; }
    }
    private int _OffsetHighLightY;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"OffsetHighLightY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OffsetHighLightY
    {
      get { return _OffsetHighLightY; }
      set { _OffsetHighLightY = value; }
    }

    private string _SpecialTip = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"SpecialTip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SpecialTip
    {
      get { return _SpecialTip; }
      set { _SpecialTip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewBieScript_ARRAY")]
  public partial class NewBieScript_ARRAY : global::ProtoBuf.IExtensible
  {
    public NewBieScript_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<NewBieScript> _items = new global::System.Collections.Generic.List<NewBieScript>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NewBieScript> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SensitiveWord")]
  public partial class SensitiveWord : global::ProtoBuf.IExtensible
  {
    public SensitiveWord() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _word;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"word", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string word
    {
      get { return _word; }
      set { _word = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SensitiveWord_ARRAY")]
  public partial class SensitiveWord_ARRAY : global::ProtoBuf.IExtensible
  {
    public SensitiveWord_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<SensitiveWord> _items = new global::System.Collections.Generic.List<SensitiveWord>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SensitiveWord> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SuperMarketGoodsInfo")]
  public partial class SuperMarketGoodsInfo : global::ProtoBuf.IExtensible
  {
    public SuperMarketGoodsInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _resid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"resid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string resid
    {
      get { return _resid; }
      set { _resid = value; }
    }
    private string _groupId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private float _price;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float price
    {
      get { return _price; }
      set { _price = value; }
    }

    private string _atlas = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"atlas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string atlas
    {
      get { return _atlas; }
      set { _atlas = value; }
    }

    private string _remark = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"remark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string remark
    {
      get { return _remark; }
      set { _remark = value; }
    }

    private int _count = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }

    private string _sound = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sound
    {
      get { return _sound; }
      set { _sound = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SuperMarketGoodsInfo_ARRAY")]
  public partial class SuperMarketGoodsInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public SuperMarketGoodsInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<SuperMarketGoodsInfo> _items = new global::System.Collections.Generic.List<SuperMarketGoodsInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SuperMarketGoodsInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimelineInfo")]
  public partial class TimelineInfo : global::ProtoBuf.IExtensible
  {
    public TimelineInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _scene_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"scene_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string scene_name
    {
      get { return _scene_name; }
      set { _scene_name = value; }
    }

    private int _player_mode = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int player_mode
    {
      get { return _player_mode; }
      set { _player_mode = value; }
    }

    private string _scene_Tag = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"scene_Tag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string scene_Tag
    {
      get { return _scene_Tag; }
      set { _scene_Tag = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _game_flow_2 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"game_flow_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> game_flow_2
    {
      get { return _game_flow_2; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _game_flow_3 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"game_flow_3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> game_flow_3
    {
      get { return _game_flow_3; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _game_flow_4 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"game_flow_4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> game_flow_4
    {
      get { return _game_flow_4; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimelineInfo_ARRAY")]
  public partial class TimelineInfo_ARRAY : global::ProtoBuf.IExtensible
  {
    public TimelineInfo_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<TimelineInfo> _items = new global::System.Collections.Generic.List<TimelineInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TimelineInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}