# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_ITEMSINFO_PRICE = descriptor.Descriptor(
  name='Price',
  full_name='TableProto.ItemsInfo.Price',
  filename='itemsinfo.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='price_dq', full_name='TableProto.ItemsInfo.Price.price_dq', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='price_gold', full_name='TableProto.ItemsInfo.Price.price_gold', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='price_value', full_name='TableProto.ItemsInfo.Price.price_value', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_ITEMSINFO_GOODSATTR = descriptor.Descriptor(
  name='GoodsAttr',
  full_name='TableProto.ItemsInfo.GoodsAttr',
  filename='itemsinfo.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='attr_type', full_name='TableProto.ItemsInfo.GoodsAttr.attr_type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attr_value', full_name='TableProto.ItemsInfo.GoodsAttr.attr_value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_ITEMSINFO = descriptor.Descriptor(
  name='ItemsInfo',
  full_name='TableProto.ItemsInfo',
  filename='itemsinfo.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='TableProto.ItemsInfo.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='TableProto.ItemsInfo.name', index=1,
      number=2, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sex', full_name='TableProto.ItemsInfo.sex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='level_limit', full_name='TableProto.ItemsInfo.level_limit', index=3,
      number=4, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='club_vip_level', full_name='TableProto.ItemsInfo.club_vip_level', index=4,
      number=5, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='qb_2', full_name='TableProto.ItemsInfo.qb_2', index=5,
      number=6, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='consume_type', full_name='TableProto.ItemsInfo.consume_type', index=6,
      number=7, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time_unit', full_name='TableProto.ItemsInfo.time_unit', index=7,
      number=8, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_online', full_name='TableProto.ItemsInfo.is_online', index=8,
      number=9, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='can_buy', full_name='TableProto.ItemsInfo.can_buy', index=9,
      number=10, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='can_recharge', full_name='TableProto.ItemsInfo.can_recharge', index=10,
      number=11, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='online_time', full_name='TableProto.ItemsInfo.online_time', index=11,
      number=12, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='offline_time', full_name='TableProto.ItemsInfo.offline_time', index=12,
      number=13, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='privileged_plat_id_list', full_name='TableProto.ItemsInfo.privileged_plat_id_list', index=13,
      number=14, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='privileged_plat_is_online', full_name='TableProto.ItemsInfo.privileged_plat_is_online', index=14,
      number=15, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='privileged_plat_can_buy', full_name='TableProto.ItemsInfo.privileged_plat_can_buy', index=15,
      number=16, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='privileged_plat_can_recharge', full_name='TableProto.ItemsInfo.privileged_plat_can_recharge', index=16,
      number=17, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payment_terms', full_name='TableProto.ItemsInfo.payment_terms', index=17,
      number=18, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='valid_time', full_name='TableProto.ItemsInfo.valid_time', index=18,
      number=19, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sort_priority', full_name='TableProto.ItemsInfo.sort_priority', index=19,
      number=20, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='suit_number', full_name='TableProto.ItemsInfo.suit_number', index=20,
      number=21, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bag_sort_priority', full_name='TableProto.ItemsInfo.bag_sort_priority', index=21,
      number=22, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='TableProto.ItemsInfo.status', index=22,
      number=23, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rank', full_name='TableProto.ItemsInfo.rank', index=23,
      number=24, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='price_discount', full_name='TableProto.ItemsInfo.price_discount', index=24,
      number=25, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vip_discount', full_name='TableProto.ItemsInfo.vip_discount', index=25,
      number=26, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='price_table', full_name='TableProto.ItemsInfo.price_table', index=26,
      number=27, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='goods_attr', full_name='TableProto.ItemsInfo.goods_attr', index=27,
      number=28, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='TableProto.ItemsInfo.description', index=28,
      number=29, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='limit_id', full_name='TableProto.ItemsInfo.limit_id', index=29,
      number=30, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='subSystemId', full_name='TableProto.ItemsInfo.subSystemId', index=30,
      number=31, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ITEMSINFO_ARRAY = descriptor.Descriptor(
  name='ItemsInfo_ARRAY',
  full_name='TableProto.ItemsInfo_ARRAY',
  filename='itemsinfo.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='items', full_name='TableProto.ItemsInfo_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ITEMSINFO.fields_by_name['price_table'].message_type = _ITEMSINFO_PRICE
_ITEMSINFO.fields_by_name['goods_attr'].message_type = _ITEMSINFO_GOODSATTR
_ITEMSINFO_ARRAY.fields_by_name['items'].message_type = _ITEMSINFO

class ItemsInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Price(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ITEMSINFO_PRICE
  
  class GoodsAttr(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ITEMSINFO_GOODSATTR
  DESCRIPTOR = _ITEMSINFO

class ItemsInfo_ARRAY(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ITEMSINFO_ARRAY

