# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_MAINANIMATION_ACT_ATTR = descriptor.Descriptor(
  name='act_attr',
  full_name='TableProto.MainAnimation.act_attr',
  filename='mainanimation.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='act_name', full_name='TableProto.MainAnimation.act_attr.act_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='act_sound', full_name='TableProto.MainAnimation.act_attr.act_sound', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time', full_name='TableProto.MainAnimation.act_attr.time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delay_time', full_name='TableProto.MainAnimation.act_attr.delay_time', index=3,
      number=4, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='act_des', full_name='TableProto.MainAnimation.act_attr.act_des', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAINANIMATION = descriptor.Descriptor(
  name='MainAnimation',
  full_name='TableProto.MainAnimation',
  filename='mainanimation.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='TableProto.MainAnimation.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='special_act', full_name='TableProto.MainAnimation.special_act', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='enable', full_name='TableProto.MainAnimation.enable', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='act_table', full_name='TableProto.MainAnimation.act_table', index=3,
      number=4, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MAINANIMATION_ARRAY = descriptor.Descriptor(
  name='MainAnimation_ARRAY',
  full_name='TableProto.MainAnimation_ARRAY',
  filename='mainanimation.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='items', full_name='TableProto.MainAnimation_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MAINANIMATION.fields_by_name['act_table'].message_type = _MAINANIMATION_ACT_ATTR
_MAINANIMATION_ARRAY.fields_by_name['items'].message_type = _MAINANIMATION

class MainAnimation(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class act_attr(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MAINANIMATION_ACT_ATTR
  DESCRIPTOR = _MAINANIMATION

class MainAnimation_ARRAY(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MAINANIMATION_ARRAY

